version: "1"

services:

  dashboard:
    image: node:carbon
    command: npm run start
    depends_on: 
      - db
    ports:
      - 8080:8080
  
  api:
    image: node:carbon
    command: npm run start
    depends_on: 
      - db
    ports:
      - 8080:8080

  backup:
    build: ./backup
    container_name: db_postgresql
    command: python scheduler.py
    depends_on: 
      - db
    ports:
      - 8080:8080

  db_postgresql:
    image: postgres:9.4
    container_name: db_postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: apidb