version: "3"

services:

  db:
    image: postgres:9.4
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: apidb
  
  api:
    image: node:carbon
    build: ./api
    command: npm run build && npm run serve
    depends_on: 
      - db
    ports:
      - 3000:3000

  backup:
    image: python:3.6.4
    build: ./backup
    command: pip install -r requirements.txt && python scheduler.py -mi 1
    depends_on: 
      - api

  dashboard:
    image: node:carbon
    build: ./dashboard
    command: npm run start
    ports:
      - 8080:8080
    depends_on: 
      - api