version: "3"

services:

  bitso_db:
    image: postgres:9.4
    container_name: bitso_posgresql
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
  
  bitso_api:
    image: node:carbon
    container_name: bitso_api
    build: ./api
    command: npm run serve
    depends_on: 
      - bitso_db
    ports:
      - "3000:3000"
    expose:
      - "3000"
    environment:
      NODE_ENV: https://api.bitso.com
      JWT_SECRET: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
      DATABASE_URL: postgres://postgres:1234@bitso_db:5432/postgres

  backup:
    image: python:3.6.4
    container_name: bitso_backup
    build: ./backup
    command: python scheduler.py
    depends_on: 
      - bitso_api
    environment:
      BITSO_API: https://api.bitso.com
      BACKUP_API: http://bitso_api:3000
      AUTHORIZATION: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
      MINUTES: 1

  bitso_dashboard:
    image: node:carbon
    container_name: bitso_dashboard
    build: ./dashboard
    command: serve -s build
    ports:
      - "5000:5000"
    depends_on: 
      - bitso_api