version: "3"

services:

  db:
    image: postgres:9.4
    container_name: bitso_posgresql
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
  
  api:
    image: node:carbon
    container_name: bitso_api
    working_dir: /app/
    build: ./api
    command: npm run serve
    depends_on: 
      - db
    ports:
      - "3000:3000"
    expose:
      - "3000"
    environment:
      - NODE_ENV="https://api.bitso.com"
      - JWT_SECRET="http://localhost:3000"
      - DATABASE_URL="postgres://postgres:1234@db:5432/postgres"

  #backup:
    #image: python:3.6.4
    #container_name: bitso_backup
    #working_dir: /home/src/app
    #build: ./backup
    #depends_on: 
    #  - api
    #environment:
    #  - BITSO_API="https://api.bitso.com"
    #  - BACKUP_API="http://localhost:3000"
    #  - AUTHORIZATION="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9"

 # dashboard:
    #image: node:carbon
    #container_name: bitso_dashboard
    #working_dir: /home/src/app/
    #build: ./dashboard
    #command: npm run serve
    #ports:
    #  - "8080:8080"
    #expose:
    #  - "8080"
    #depends_on: 
    #  - api