version: "3"

services:

  db:
    image: postgres:9.4
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
  
  api:
    image: node:carbon
    working_dir: /home/node/app
    build: ./api
    command: npm run serve
    depends_on: 
      - db
    ports:
      - 3000:3000

  backup:
    image: python:3.6.4
    working_dir: /home/python/app
    build: ./backup
    command: run.sh
    depends_on: 
      - api

  dashboard:
    image: node:carbon
    working_dir: /home/node/app
    build: ./dashboard
    command: npm run serve
    ports:
      - 8080:8080
    depends_on: 
      - api